version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: php
    working_dir: /var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: yii2user
      POSTGRES_PASSWORD: yii2password
      POSTGRES_DB: yii2db
    ports:
      - "5432:5432"
